Organization of utkscan header files
pixie16/paass pull request #104
Opened 2016-09-22 16:21 UTC by spaulaus

These headers were making the directory unreadable and impossible quickly find information. The files have been reorganized and the source files updated to reflect this change.

2016-09-22 16:26 UTC, ksmith0 commented
This isn't what I expected. I would have gone the other way and had the following:
utkscan
|-analyzers
| |-include
| |-source
|-core
| |-include
| |-source
...

2016-09-22 16:31 UTC, ksmith0 commented
Also, I dislike putting paths in the include statements as the movement of one header file requires touching everything that uses it. I prefer to let the compiler figure out where the files are.

2016-09-22 16:40 UTC, spaulaus commented
Fair point (though moot with IDEs.....). I like the suggestion and will make the correction.

2016-09-22 17:42 UTC, spaulaus commented
@ksmith0 How does this strike your fancy?

2016-09-22 17:48 UTC, ksmith0 commented on Scan/utkscan/CMakeLists.txt
> +include_directories(include processors/include)
Why do you repeatedly add the include directory?
Does all the following source need all these includes?

2016-09-22 17:49 UTC, ksmith0 requested changes
I would have expected something like

``` cmake
#All utkscan source needs the following headers
include_directories(core/include)

add_subdirectory(core/source)

add_subdirectory(analyzers)
add_subdirectory(processors)
add_subdirectory(experiments)
```

And the CMakeLists.txt in analyzers etc would have

``` cmake
include_directories(include)
add_subdirectory(source)
```

2016-09-22 17:50 UTC, spaulaus commented on Scan/utkscan/CMakeLists.txt
> +include_directories(include processors/include)
Not all of it, but it's such a mixed bag that it's easier than cherry picking which ones need it and which do not. Remember that we have a mess of circular dependencies here.

2016-09-22 17:50 UTC, ksmith0 commented on Scan/utkscan/CMakeLists.txt
> +include_directories(include ../ScanLib/include)
This line shouldn't be here. the ScanLib/include is added in the parent CMakeLists.txt

2016-09-22 17:51 UTC, ksmith0 commented on Scan/utkscan/CMakeLists.txt
> +include_directories(include processors/include)
Ok I'll accept that, but you need to drop the repeated addition of the include folder.

2016-09-22 17:53 UTC, spaulaus commented on Scan/utkscan/CMakeLists.txt
> +include_directories(include ../ScanLib/include)
When removing this line, I get a compilation error 
```
[ 84%] Building CXX object Scan/utkscan/core/source/CMakeFiles/CoreObjects.dir/utkscan.cpp.o
In file included from /home/vincent/programs/sources/utk/paass/Scan/utkscan/core/include/UtkScanInterface.hpp:7:0,
                 from /home/vincent/programs/sources/utk/paass/Scan/utkscan/core/source/utkscan.cpp:4:
/opt/PixieSuite2/include/ScanInterface.hpp:127:24: error: ‘XiaData’ has not been declared
  virtual bool AddEvent(XiaData *event_){ return false; }
                        ^~~~~~~
make[3]: *** [Scan/utkscan/core/source/CMakeFiles/CoreObjects.dir/build.make:447: Scan/utkscan/core/source/CMakeFiles/CoreObjects.dir/utkscan.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/Makefile2:657: Scan/utkscan/core/source/CMakeFiles/CoreObjects.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
[ 84%] Built target ProcessorObjects
make[1]: *** [CMakeFiles/Makefile2:559: Scan/utkscan/CMakeFiles/utkscan.dir/rule] Error 2
make: *** [Makefile:266: utkscan] Error 2
```

2016-09-22 17:53 UTC, ksmith0 commented
I clearly do not know how to use this review process yet. The requested changes are removal of 
```cmake
include_directories(include ../ScanLib/include)
```
and remove repeated `include` from
```cmake
include_directories(include analyzers/include)
include_directories(include core/include)
include_directories(include experiment/include)
include_directories(include processors/include)
```

2016-09-22 18:20 UTC, spaulaus commented
I think we did exactly the same things....

2016-09-22 18:23 UTC, ksmith0 commented
I see you resolved the `BUILD_UTKSCAN_TESTS` issue. I propose that before we merge this we (you) move the tests folder to live inside analyzers. Either analyzers/tests or analyzers/source/tests

2016-09-22 18:27 UTC, ksmith0 requested changes
Changes to include_directories is good. Propose we also move tests while we are at it, I imagine the same thing will happen with them in the future.

2016-09-22 18:34 UTC, spaulaus commented
I can see some merit in this. Though, each of the directories will get their own tests folders eventually. I was trying to centrally locate the tests, but as you say with the includes/sources it may make more sense to colocate all of them together.

2016-09-22 18:36 UTC, ksmith0 commented
I agree that each one will eventually get a test folder. This is also already true for `Core/tests`. Is the plan to move tests or not?

2016-09-22 18:37 UTC, spaulaus commented
None of the core files have tests yet. I apologize for not being clear. I agree with the move of tests from utkscan/tests to utkscan/analyzers/tests.

2016-09-22 18:38 UTC, ksmith0 commented
Yes they [do](https://github.com/pixie16/paass/tree/master/Core/tests), although it is more of a test program. (Some info about use in issue #70)

2016-09-22 18:39 UTC, spaulaus commented
Oh sorry! We have two "Cores" there's a core for utkscan as well, which is what I assumed was the reference given that this thread is mostly about that!

2016-09-22 18:40 UTC, ksmith0 commented
Ahh yeah, that is confusing.

2016-09-23 12:57 UTC, spaulaus commented
@ksmith0 The request changes have been made. The organization is a little tighter, and more expansible.

2016-09-23 13:25 UTC, ksmith0 approved these changes
Looks good. Squash and merge?

2016-09-23 15:34 UTC, spaulaus commented
Do it.

2016-09-23 15:34 UTC, merged