Updating pspmt processor
pixie16/paass pull request #278
Opened 2017-06-06 20:46 UTC by akeeler

updating PSPMT processor to the version used for the e14060 experiment

2017-06-07 01:43 UTC, spaulaus commented
I will review this once @ksmith0 and I complete PR #269

2017-06-07 01:50 UTC, tking53 commented
Im using this as a teaching opportunity. So that Andrew and Maninder can learn how to review pull requests.

2017-06-07 01:55 UTC, spaulaus commented
> Im using this as a teaching opportunity. So that Andrew and Maninder can learn how to review pull requests.

Ok, @ksmith0 and I will be working this week to knock out my giant PR. If this gets merged before then, I'll make sure I follow the rules.

2017-06-07 11:14 UTC, spaulaus requested changes
I don't see any major issues. I've noted some of the comments that should be revised.

2017-06-07 11:14 UTC, spaulaus commented on Analysis/Utkscan/core/source/DetectorDriverXmlParser.cpp
> +                    processor.attribute("vd").as_string(),
You should probably have this provide a default value. I suggest defaulting to the version used in the experiment.

2017-06-07 11:14 UTC, spaulaus commented on Analysis/Utkscan/processors/include/PspmtProcessor.hpp
> +///@authors S. Go and S. V. Paulauskas
@akeeler : make sure you add your name to this list. You've contributed more to the file than just style changes.

2017-06-07 11:14 UTC, spaulaus commented on Analysis/Utkscan/processors/include/PspmtProcessor.hpp
> +    PspmtProcessor(void) {};
You don't really need the void in here.

2017-06-07 11:14 UTC, spaulaus commented on Analysis/Utkscan/processors/include/PspmtProcessor.hpp
> +    PspmtProcessor(const std::string &vd, const double &scale,
We've updated the line length limits to 130 characters. Maybe update these files to that limit. It will prevent line breaks in funny places.

2017-06-07 11:14 UTC, spaulaus commented on Analysis/Utkscan/processors/include/PspmtProcessor.hpp
> +    std::pair<std::map<std::string, double>::iterator, bool> InsertMapValue
Another case where 130 line limit is helpful.

2017-06-07 11:14 UTC, spaulaus commented on Analysis/Utkscan/processors/source/PspmtProcessor.cpp
> +///@authors S. Go and S. V. Paulauskas
Again add @akeeler  to this list.

2017-06-07 11:14 UTC, spaulaus commented on Analysis/Utkscan/processors/source/PspmtProcessor.cpp
> +PspmtProcessor::PspmtProcessor(const std::string &vd, const double &scale,
130 line limit.

2017-06-07 14:12 UTC, tking53 commented on Analysis/Utkscan/processors/include/PspmtProcessor.hpp
> +    PspmtProcessor(const std::string &vd, const double &scale,
this is my bad i had him correct to 80. i saw that you had discussed it but not that it was implemented

2017-06-07 18:31 UTC, ksmith0 commented
We are trying to avoid merges by doing rebases to make the history more readable. I'll correct this.

2017-06-07 18:38 UTC, ksmith0 requested changes
We are trying to avoid merges. Also, it seems that this is a trivial merge between two of the exact same commit?

You should correct this by using the following commands:

```
git checkout UpdatingPSPMTprocessor
git reset --hard 5ce8d88
git push --force
```

2017-06-07 19:57 UTC, akeeler commented
@ksmith0  Reverted and pushed, but it looks like the timestamp on the commit hasn't changed

2017-06-07 23:10 UTC, spaulaus commented on Analysis/Utkscan/processors/include/PspmtProcessor.hpp
> +    PspmtProcessor(void) {};
You should also remove the `*/` from the end of the line to avoid confusion.

2017-06-08 02:13 UTC, spaulaus commented
I'm closing this PR. It looks like too many things got borked. Let's try to do it cleanly with the next one.

2017-06-08 02:13 UTC, closed without merging